PROJECT_NAME = "SmartDoc"


USECASES = "USECASES"

LANGCHAIN = "langchain"
CHATGLM_PATH = "CHATGLM_PATH"
VICUNA_PATH  = "VICUNA_PATH"
WHISPER_SMALL_PATH ="WHISPER_SMALL_PATH"


AZURE = "azure"
GPT_3DOT5_TURBO = "gpt-3.5-turbo"
GPT_35_TURBO_16K= "gpt-35-turbo-16k"
TEXT_EMBEDDING_ADA_002 ="text-embedding-ada-002"
# "text-davinci-003"
OPENAI_EMBEDDING_MAX_INPUT_NUM=16

ENGLISH = "ENGLISH"
CHINESE = "CHINESE"
DATA="data"
VECTOR_STORES= "vector_stores"
SOURCE_DOC ="SOURCE_DOC"
AADQ_FAQ_DOC = "AADQ_FAQ_DOC"
AADQ_API_DOC= "AADQ_API_DOC"

RESULT= "result"
SOURCE_DOCUMENTS = "source_documents"
NLTK_DATA ="NLTK_DATA"
TIKTOKEN_CACHE_DIR= "TIKTOKEN_CACHE_DIR"
FAISS = "FAISS"
DOCARRAY_INMEMORY_SEARCH ="DOCARRAY_INMEMORY_SEARCH"


OPENAI_API_KEY = "OPENAI_API_KEY"
OPENAI_API_BASE = "OPENAI_API_BASE"
DEPLOYMENT_NAME ="DEPLOYMENT_NAME"
OPENAI_API_VERSION= "OPENAI_API_VERSION"

DEFAULT_ENCODING = 'utf-8'

# Snowflake related
SNOWFLAKE = "SNOWFLAKE"
SNOWFLAKE_USER = "_".join([SNOWFLAKE, "USER"])
SNOWFLAKE_PASSWORD = "_".join([SNOWFLAKE, "PASSWORD"])
SNOWFLAKE_ACCOUNT_IDENTIFIER = "_".join([SNOWFLAKE, "ACCOUNT", "IDENTIFIER"])